@host = https://localhost:7128
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYjFiMWQxNS00MDZlLTQxYTgtOWIwOC01NDg0YTMzNzhlZTgiLCJnaXZlbl9uYW1lIjoiQW1pY2hhaSIsImZhbWlseV9uYW1lIjoiTWFudGluYmFuZCIsImp0aSI6ImM0MWU5ZThkLWJiOGEtNDA0Ni05ZWFhLTRkMTczZDhjNDg0NSIsImV4cCI6MTcxNjUyNTg2NiwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.3nlidxHi1DM-w5hzd4XZURolJNxFew8Fg20M7WEHggc
@hostId = asdasd

Post  {{host}}/host/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "Start Meal",
    "sections": [
        {
            "name": "Yummy Menu Section",
            "description": "Start Meal Section",
            "items": [
                {
                    "name": "Yummy Menu Item",
                    "description": "Start Meal Item"
                }
            ]
        }
    ]
}