@host = https://localhost:7128
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjYjFiMWQxNS00MDZlLTQxYTgtOWIwOC01NDg0YTMzNzhlZTgiLCJnaXZlbl9uYW1lIjoiQW1pY2hhaSIsImZhbWlseV9uYW1lIjoiTWFudGluYmFuZCIsImp0aSI6ImI1NzFhZWFlLWIxMzctNDQwMC1iYmVkLTA1MmQ5NDIxNGM1ZiIsImV4cCI6MTcxODI2Mzk3MiwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.1zotQ7SN06DMfoSycQk-9mNW0AcOxKSOiVmFHwnkc9c
@hostId = asdasd

Post  {{host}}/host/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "Start Meal",
    "sections": [
        {
            "name": "Yummy Menu Section",
            "description": "Start Meal Section",
            "items": [
                {
                    "name": "Yummy Menu Item",
                    "description": "Start Meal Item"
                }
            ]
        }
    ]
}